#!/bin/bash
# Test script for musical note placement variations
# Run this to see different variations and pick your favorite!

echo "=== Musical Note Placement Variations ==="
echo ""
echo "Review each variation and let me know which looks best!"
echo ""

echo "============================================"
echo "VARIATION 1: Current Implementation"
echo "- Notes in prefix/suffix (♪ text ♫)"
echo "- Notes interspersed in border (~♪~♪~)"
echo "- Musical note connector (♪)"
echo "============================================"
./familiar-says --bubble-style song "La la la, I love to sing!"
echo ""

echo "============================================"
echo "VARIATION 2: Notes on border only"
echo "(simulated - actual would need template change)"
echo "============================================"
echo " ♪~~~~~~~~~~~~~~♪ "
echo "│ La la la sing │"
echo " ♪~~~~~~~~~~~~~~♪ "
echo "    ♪"
echo "     ♪"
echo ""

echo "============================================"
echo "VARIATION 3: Notes floating outside"
echo "(simulated - actual would need template change)"
echo "============================================"
echo "♪  ____________  ♪"
echo "  < Singing! >   "
echo "♫  ----------  ♫"
echo "    \\"
echo ""

echo "============================================"
echo "VARIATION 4: Dense musical border"
echo "(simulated - actual would need template change)"
echo "============================================"
echo " ♪♫♪♫♪♫♪♫♪♫♪♫♪♫ "
echo "│ La la la la │"
echo " ♪♫♪♫♪♫♪♫♪♫♪♫♪♫ "
echo "    ♪"
echo ""

echo "============================================"
echo "VARIATION 5: Notes in corners"
echo "(simulated - actual would need template change)"
echo "============================================"
echo "♪~~~~~~~~~~~♫"
echo "│ Singing! │"
echo "♫~~~~~~~~~~~♪"
echo "    ~"
echo ""

echo "============================================"
echo "VARIATION 6: Long text test"
echo "============================================"
./familiar-says --bubble-style song "When the moon hits your eye like a big pizza pie, that is amore!"
echo ""

echo "============================================"
echo "VARIATION 7: Multi-line song"
echo "============================================"
./familiar-says --bubble-style song --width 25 "Row row row your boat gently down the stream merrily merrily life is but a dream"
echo ""

echo ""
echo "Which variation do you prefer? Let me know and I can implement that style!"
